# Generated by Django 3.2.12 on 2022-04-21 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='إسم الكتاب')),
                ('summary', models.CharField(max_length=1000, verbose_name='نبذه مختصره عن الكتاب')),
                ('author', models.CharField(max_length=1000, verbose_name='إسم المؤلف')),
                ('language', models.CharField(choices=[('EN', 'EN'), ('عربي', 'عربي')], default='EN', max_length=100, verbose_name='لغة الكتاب ')),
                ('pic_book', models.ImageField(blank=True, null=True, upload_to='book_image')),
                ('pdf_File', models.FileField(blank=True, null=True, upload_to='book_pdf')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='الرجاء كتابة التصنيفات التي سيتم إدراج الكتب تحتها ( إسلامي , تاريخي , مجلة علمية .... إلخ )', max_length=200, verbose_name='إسم القسم')),
            ],
        ),
        migrations.CreateModel(
            name='project_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='الإسم')),
                ('school_level', models.CharField(max_length=30, verbose_name='المرحلة الدراسية')),
                ('information_me', models.CharField(max_length=30, verbose_name=' نبذة شخصية')),
            ],
        ),
        migrations.CreateModel(
            name='scoole_appoitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='  الرجاء تحديد إسم المدرسة مع المرحلة الدراسية', max_length=30, verbose_name='إسم المدرسة')),
                ('staff_name', models.CharField(help_text=' إسم المشرفة المسؤولة عن طلب الزيارة ', max_length=30, verbose_name='إسم المشرفه')),
                ('student_count', models.IntegerField(help_text=' عدد الطالبات المتوقع حضورهم ', verbose_name='عدد الطالبات')),
                ('appoitment_dt', models.DateField(help_text=' تاريخ الزياره ', null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='site_viwes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default='none', max_length=100)),
                ('rating', models.CharField(choices=[('0', '0'), ('.5', '.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='2', max_length=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libary_app.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libary_app.category', verbose_name='إسم القسم'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
