# Generated by Django 3.2.12 on 2022-04-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_viwes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.CharField(max_length=200)),
            ],
        ),
    ]
